
package registry.ca.rt;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RegistryService", targetNamespace = "http://rt.ca.registry/", wsdlLocation = "http://10.215.0.155/GUC_Registry/Services/RegistryService.asmx?wsdl")
public class RegistryService
    extends Service
{

    private final static URL REGISTRYSERVICE_WSDL_LOCATION;
    private final static WebServiceException REGISTRYSERVICE_EXCEPTION;
    private final static QName REGISTRYSERVICE_QNAME = new QName("http://rt.ca.registry/", "RegistryService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.215.0.155/GUC_Registry/Services/RegistryService.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        REGISTRYSERVICE_WSDL_LOCATION = url;
        REGISTRYSERVICE_EXCEPTION = e;
    }

    public RegistryService() {
        super(__getWsdlLocation(), REGISTRYSERVICE_QNAME);
    }

    public RegistryService(WebServiceFeature... features) {
        super(__getWsdlLocation(), REGISTRYSERVICE_QNAME, features);
    }

    public RegistryService(URL wsdlLocation) {
        super(wsdlLocation, REGISTRYSERVICE_QNAME);
    }

    public RegistryService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, REGISTRYSERVICE_QNAME, features);
    }

    public RegistryService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RegistryService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RegistryServiceSoap
     */
    @WebEndpoint(name = "RegistryServiceSoap")
    public RegistryServiceSoap getRegistryServiceSoap() {
        return super.getPort(new QName("http://rt.ca.registry/", "RegistryServiceSoap"), RegistryServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RegistryServiceSoap
     */
    @WebEndpoint(name = "RegistryServiceSoap")
    public RegistryServiceSoap getRegistryServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://rt.ca.registry/", "RegistryServiceSoap"), RegistryServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (REGISTRYSERVICE_EXCEPTION!= null) {
            throw REGISTRYSERVICE_EXCEPTION;
        }
        return REGISTRYSERVICE_WSDL_LOCATION;
    }

}
